### ISSUE TITLE
Log file creation problem

### ISSUE THREAD

**Issue by selfus** [jjgomera/pychemqt#2]
On the first run of pychemqt, with python 3.4.3 and pyqt5, both for x64 windows, I am having the current issue
Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\pychemqt-py3qt5\pychemqt.py", line 62, in <module>
    format='[%(asctime)s.%(msecs)d] %(levelname)s: %(message)s')
  File "C:\Python34\lib\logging\__init__.py", line 1739, in basicConfig
    h = FileHandler(filename, mode)
  File "C:\Python34\lib\logging\__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python34\lib\logging\__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Pedro\\.pychemqt\\pychemqt.log'

**Comment by jjgomera** [comment]
Fixed in last commit
Thanks!!!

PD: I see you are using the py3qt5 branch, thats it's a development branch, very unstable and incomplete in version transition process, so i don't recommend you use it, use instead the default master branch.
